Create task for sync job status check
kestra-io/plugin-dbt pull request #63
Opened 2023-09-28 13:43 UTC by aballiet

Fixes https://github.com/kestra-io/plugin-dbt/issues/62

2023-09-28 13:56 UTC, aballiet commented
A quick note regarding reproducibility locally, for dbt plugin, when setting parseRunResults(true), run is failing because : https://github.com/kestra-io/plugin-dbt/blob/65ac06fdd112e547be673e9a45ba1fcbf0298ac7/src/main/java/io/kestra/plugin/dbt/ResultParser.java#L90

<img width="1128" alt="image" src="https://github.com/kestra-io/plugin-dbt/assets/25565600/829e16dc-2c72-4bc8-8abf-2bcf2d63fd22">

2023-09-28 14:12 UTC, brian-mulier-p requested changes
Thank's a lot ! :+1:

2023-09-28 14:12 UTC, brian-mulier-p commented on src/main/java/io/kestra/plugin/dbt/cloud/CheckStatus.java
> +        title = "Check Job status of a running job"
```suggestion
        title = "Check job status of a running job"
```

2023-09-28 14:12 UTC, brian-mulier-p commented on src/main/java/io/kestra/plugin/dbt/cloud/CheckStatus.java
> +            title = "Specify frequency for job state check API calls"
```suggestion
            title = "Specify frequency at which the job status will be checked"
```

2023-09-28 14:12 UTC, brian-mulier-p commented on src/main/java/io/kestra/plugin/dbt/cloud/TriggerRun.java
>  public class TriggerRun extends AbstractDbtCloud implements RunnableTask<TriggerRun.Output> {
loggedSteps & loggedStatus aren't used anymore there am I wrong ?

2023-09-28 14:16 UTC, aballiet commented on src/main/java/io/kestra/plugin/dbt/cloud/TriggerRun.java
>  public class TriggerRun extends AbstractDbtCloud implements RunnableTask<TriggerRun.Output> {
Correct !

2023-09-28 14:20 UTC, aballiet commented on src/main/java/io/kestra/plugin/dbt/cloud/TriggerRun.java
>  public class TriggerRun extends AbstractDbtCloud implements RunnableTask<TriggerRun.Output> {
Fixed 👍

2023-09-28 15:32 UTC, anna-geller approved these changes
functionality-wise, LGTM

Thanks for adding this 👍

2023-09-28 15:32 UTC, anna-geller commented on src/main/java/io/kestra/plugin/dbt/cloud/CheckStatus.java
> +        title = "Check job status of a running job"
```suggestion
        title = "Check the status of a dbt Cloud job"
```

2023-09-28 15:32 UTC, anna-geller commented on src/main/java/io/kestra/plugin/dbt/cloud/CheckStatus.java
> +            title = "The run id to check status for"
```suggestion
            title = "The job run id to check the status for"
```

2023-09-28 15:32 UTC, anna-geller commented on src/main/java/io/kestra/plugin/dbt/cloud/CheckStatus.java
> +            title = "Specify frequency at which the job status will be checked"
```suggestion
            title = "Specify how often the task should poll for the job status"
```

2023-09-28 15:32 UTC, anna-geller commented on src/main/java/io/kestra/plugin/dbt/cloud/CheckStatus.java
> +            title = "The max total wait duration"
```suggestion
            title = "The maximum duration the task should poll for the job completion"
```

2023-09-28 15:32 UTC, anna-geller commented on src/main/java/io/kestra/plugin/dbt/cloud/CheckStatus.java
> +            description = "Parsing run result to display duration of each task inside dbt"
```suggestion
            description = "Whether to parse the run result to display the duration of each dbt node in the Gantt view"
```

2023-09-28 15:32 UTC, anna-geller commented on src/main/java/io/kestra/plugin/dbt/cloud/CheckStatus.java
> +                title = "URI of a run results"
```suggestion
                title = "URI of the run result"
```

2023-09-29 08:10 UTC, brian-mulier-p approved these changes
LGTM

2023-09-29 08:12 UTC, merged